### ISSUE TITLE
[Error] liff.sendMessage()

### ISSUE THREAD

**Issue by at-hoangnguyen2** [line/line-liff-v2-starter#1]
![Image from iOS](https://user-images.githubusercontent.com/26244995/66978808-83b6b400-f0d5-11e9-9263-297a12de0c29.png)
I encountered an error like the above.
How can I fix this?
Thank you !!!

Device: iPhone 7+
OS: IOS 13.1.2
Liff version: v2.1

**Comment by kami-zh** [comment]
I also had this issue and fixed this by checking `chat_message.write` scope on LIFF console. This scope is hidden initially, and you should expand by clicking label. For example, following screenshot is the console editing the scope (Language is Japanese):

![image](https://user-images.githubusercontent.com/4456532/67065728-5a1b8c80-f1aa-11e9-82d4-057143f04f04.png)

**Comment by at-hoangnguyen2** [comment]
@kami-zh Thank you so much!
