### ISSUE TITLE
support react hook about sdk.js?

### ISSUE THREAD

**Issue by natehsu** [line/line-liff-v2-starter#16]
Hi,
I am using next.js and react hook and sdk.js
the sdk url is https://static.line-scdn.net/liff/edge/2/sdk.js

I have a error when passing query string to Liff v2, 
ex: https://liff.line.me/1654356111-zzzzzzzz?userId=aaa,
But if I don't pass query string then no error.

code example:

```
useEffect(() => {
        initializeLiff('a real id')
    })

function initializeLiff(myLiffId) {
        liff
            .init({
                liffId: myLiffId
            })
            .then(() => {
                // start to use LIFF's api
                console.log('initializeLiff ok')
            })
            .catch((err) => {
                console.log(err.code, err.message);
            });
    }


return (
        <React.Fragment>
            <Head>
                <script charSet="utf-8" src="https://static.line-scdn.net/liff/edge/2/sdk.js"></script>
            </Head>
        </React.Fragment>
)

```
    
I would appreciate your help.

**Comment by smwilk** [comment]
Hi @natehsu,
Thank you for your question, and I'm very sorry about the lack of response.
Could you please share the error message you are seeing?

**Comment by natehsu** [comment]
Hi @smwilk 
Thank you for your reply.
Because it refresh page and then redirect to home page very quickly, so I could't get any error messages.
But when I monitor chrome network traffic, I got some error. Count you please check the screenshots:
https://imgur.com/xyPvIsE
https://imgur.com/qPdXnqp

Thanks

**Comment by smwilk** [comment]
Hi @natehsu,
Sorry for the late reply. Since the issue you're describing has to do with LIFF and not line-liff-v2-starter, I'd like to suggest that you contact our technical support team via [this form](https://contact.line.me/serviceId/11556).

**Comment by natehsu** [comment]
@smwilk 
Thank you for the information.
