### ISSUE TITLE
Unable to do "Open Share Target Picker"

### ISSUE THREAD

**Issue by jerryFromAjltc** [line/line-liff-v2-starter#20]
Hi there,

I've already put LIFF Starter on my site "https://gurunets.ddns.net/line/aw/line-liff-v2-starter-master/public/"

Everything works fine but the function "share target picker".

When I try pressing the button "Open Share Target Picker" inside a LINE chat on my android phone, the error message "Failed to launch share target picker" shows. Then I try to display the error message returned, its content is "Failed to have a connection from TargetPicker to SDK".

Can anyone help? Thanks.

**Comment by smwilk** [comment]
Hi @jerryFromAjltc.
Thank you for your question, and sorry for the delayed response.
The `liff.shareTargetPicker()` method is supported by v10.3.0 or later for both LINE for iOS and LINE for Android. Could you check if your LINE app satisfies this requirement?
See the [description about `liff.shareTargetPicker()`](https://developers.line.biz/en/reference/liff/#share-target-picker) for more information.
You can also catch the error returned by the `liff.isApiAvailable()` method. See the [documentation](https://developers.line.biz/en/reference/liff/#is-api-available) for more details.

I hope this helps!

**Comment by smwilk** [comment]
Closing this issue due to inaction.
