### ISSUE TITLE
LIFF uses LINE Login channel

### ISSUE THREAD

**Issue by JG-Readiness** [line/line-liff-v2-starter#21]
At here, https://github.com/line/line-liff-v2-starter/blob/master/README.md#what-youll-need
The first row in the "Item" column shows "LINE Messaging API channel", but LIFF uses LINE Login Channnel.
![image](https://user-images.githubusercontent.com/56300240/99359464-73819180-28f2-11eb-8a72-f87e0748dfdc.png)

**Comment by smwilk** [comment]
Hi @JG-Readiness, thank you for reporting this error. This issue has now been fixed.
