### ISSUE TITLE
How to get the current user's location information(GEO)?

### ISSUE THREAD

**Issue by lizhengnacl** [line/line-liff-v2-starter#23]
> When you implement an API that uses any of the device or OS functions listed below, implement the API so that user actions trigger API calls.
>
>   - Getting location information
>   - Accessing the camera
>   - Accessing the microphone

what's that mean?

https://developers.line.biz/en/docs/liff/overview/#development-guidelines

**Comment by smwilk** [comment]
Hi @lizhengnacl,
Thank you for your question, and sorry for the delayed response.
It seems that your question is about LIFF, not LIFF v2 starter app.
For issues and questions about LIFF, please post them in [LINE Developers Community](https://www.line-community.me/en/questions). 
We have also created a [contribution guide](https://github.com/line/line-liff-v2-starter/blob/master/CONTRIBUTING.md) to make the contribution process and rules clear.

Thank you again for your interest in LIFF v2 starter app.
