### ISSUE TITLE
Cannot use namespace RequiredContext as a type

### ISSUE THREAD

**Issue by maxrks** [line/line-liff-v2-starter#28]
I try to use the latest liff framework, but a compiling error occurs as following:

```
[at-loader] Checking finished with 7 errors
Error in bail mode: [at-loader] ./node_modules/@line/liff/dist/lib/uts/index.d.ts:4:14 
    TS2709: Cannot use namespace 'RequiredContext' as a type.
```

tracking into the package declaration =>
**node_modules/@line/liff/dist/lib/uts/index.d.ts**

```
import { UTS, RequiredContext, InitOptions } from '@linecorp/uts';
import { LiffCore } from '../liff';
export interface Analytics {
    context: RequiredContext;
    options?: InitOptions;
}
```
but I cannot find where the `@linecorp/uts` be, could anybody help?

**Comment by smwilk** [comment]
Hi @maxrks 

Thank you for your question!
It seems that your question is about LIFF, not LIFF v2 starter app.
For issues and questions about LIFF, please post them in [LINE Developers Community](https://www.line-community.me/en/).

Thank you again for your interest in LIFF v2 starter app.
