### ISSUE TITLE
liff not working on android device

### ISSUE THREAD

**Issue by g3david405** [line/line-liff-v2-starter#29]
Hi,
I am using React for my liff page,
here is my code,
```
  useEffect(() => {
      alert("In useEffect");
      liff.init({
        liffId: "xxxx-xxxx"
      }).then(async () => {
        alert("init success");
        const data = await liff.getProfile();
        alert(`userId is : ${data.userId}`);
        // then I use userId to call my backend for information...
      }).catch(error => {
        alert(`init error: ${error}`);
      }).finally(() => {
        alert('finally callback')
        setLoading(false);
      });
    }, [])
```
It works well on IOS device, but have 50% chance to fail on Android device.
It will alert In useEffect in first time and not going to alert init success, init error or finally callback.
It just showing the loading page that I create, not go through then, catch or finally callback,
whats the error?
thanks!!!!!
T^T

**Comment by g3david405** [comment]
Strangely, when I do this action, it works well on android device...
https://www.youtube.com/watch?v=TwoW5bmhdBE

**Comment by cm-dyoshikawa** [comment]
@g3david405 Do you use npm version LIFF SDK? If so, try the CDN version. I have experience with the same problem.

https://developers.line.biz/en/docs/liff/developing-liff-apps/#use-npm-package

> The npm package is available on a trial basis. It may be changed or deleted in the future without notice.

So the npm version will not be stable.

**Comment by kazuma0129** [comment]
@g3david405 
Thank you for your report. It has been a long time since this issue was drafted. The version of the LIFF SDK we provide and the major devices have changed, so we are closing it.
If you have any problems with this, please let our team know or re-open the issue.
Thank you.
