### ISSUE TITLE
Have some question

### ISSUE THREAD

**Issue by jicjjang** [line/line-liff-v2-starter#3]
Why didn't solve existing [LIFF project issues](https://github.com/line/line-liff-starter/issues)?
I was waiting [this problem](https://github.com/line/line-liff-starter/issues/1) for some project, 1 year.

**Comment by syleeeee** [comment]
Hi, @jicjjang 
have you read [this comment](https://github.com/line/line-liff-starter/issues/1#issuecomment-447047163) on that issue? 

I'm going to report this issue internal channel once again, but please note that the purpose of this repo is `demo` as you see. 

We might give feedback through the original issue. 

Thanks for your interest in LINE LIFF! :)

**Comment by solie** [comment]
Hi @jicjjang 
I successfully send message via LIFF after enabling the chat_message.write option in the developer account. You need to click Scope oth -> Edit and View All to reveal this option. 
Before enabling the option, I always get 403 or permission error. Now I can use both LIFF v1 or v2 to send the message.

**Comment by jicjjang** [comment]
Hi @syleeeee @solie 

Thanks for the support.
unfortunately, still reproduced same issue. lol

I finished by connecting other messengers on last year....


![스크린샷 2019-11-05 오전 12 40 17](https://user-images.githubusercontent.com/6022539/68134704-d9101380-ff65-11e9-98f9-15ff4be9cd43.png)
![KakaoTalk_Photo_2019-11-05-00-45-55](https://user-images.githubusercontent.com/6022539/68134705-d9101380-ff65-11e9-814d-b4c6715eea9f.jpeg)

**Comment by solie** [comment]
I see. Maybe it's iOS/Android issue. Could you try my development chatbot: @gfz5504a? It's working on my android also iphone (iOS v 12.2).

**Comment by smwilk** [comment]
@jicjjang Thank you for your interest in the LIFF starter app, and I sincerely apologize for the lack of response to your question. As @solie mentioned, currently LIFF requires the `chat_message.write` scope to send a message on behalf of the user.
Please also note that once adding the scope, the LIFF app must be reopened to reflect the updated configuration.
