### ISSUE TITLE
Is README.md file still undergoing?

### ISSUE THREAD

**Issue by coldicecoffee** [line/line-liff-v2-starter#39]
**Describe the bug**
[README.md](https://github.com/line/line-liff-v2-starter/blob/master/README.md) states to run `npm ci` and `npm start` but both command does not work due to the missing `package-lock.json` and `start` script from `package.json`.

**To Reproduce**
1. Run `git clone https://github.com/line/line-liff-v2-starter.git`
2. Run `git checkout master`
3. Run `npm ci` from the top-level directory.
4. See error:
```zsh
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
```

**Expected behavior**
After running `npm ci`, all the dependencies should be installed without an error.

**Additional context**
Let me know if this README.md is still in process :)

**Comment by zenizh** [comment]
The README is a little outdated now and needs to be updated. To get it working for now, run the following

1. In the `src` directory, you will find the source code for Vanilla JS, Next.js, and Nuxt.js. For example, go to `src/vanilla`.

    ```bash
    $ cd src/vanilla
    ```

2. In it, install the packages and start the local server.

    ```bash
    $ yarn install
    $ yarn dev
    ```

3. If you access [localhost:3000](http://localhost:3000), you will see the page.

All you need is Node.js and Yarn. I'm happy to be of help.

**Comment by coldicecoffee** [comment]
Thanks a lot Hiroki! I will close this issue :)
